#! /usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Packman, just another Laravel package boilerplate generator.', '1.0.1');
$app->add(new Packman\NewCommand);
$app->run();
