#! /usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Packman\NewCommand;

$app = new Application();
$app->add(new NewCommand);
$app->run();
